name: hajir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cached_network_image: ^3.1.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  # easyqrimage: ^0.0.2
  esys_flutter_share_plus: ^2.2.0
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  get: 4.6.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_annotation: null
  local_auth: ^2.1.3
  path_provider: ^2.0.12
  percent_indicator: ^4.2.2
  permission_handler: ^10.2.0
  qrscan: ^0.3.3
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^20.4.41
  tuple: ^2.0.0
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
