name: hajir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cached_network_image: ^3.1.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  get: 4.6.5
  intl: ^0.17.0
  json_annotation: null
  local_auth: ^2.1.3
  percent_indicator: ^4.2.2
  syncfusion_flutter_charts: ^20.4.41
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
