
# name: CI
# on: 
#   pull_request:
#     branches:
#       - main

# jobs:
#   flutter_test:
#     name: Run flutter test and analyze and build apk
#     runs-on: ubuntu-latest
#     steps: 
#       - uses: actions/checkout@v3
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.0.1'
#           channel: "stable"
#       - run: flutter pub get
#       # - run: flutter analyze
#       # - run: flutter test
#       - run: flutter build apk --release --split-per-abi
#       - name: Push to Releases
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "build/app/outputs/apk/release/*"
#           tag: v1.0.${{github.run_number}}
#           token: ${{secrets.TOKEN}}



# 1
on:
  # 2
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      # 10   
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.3.9"
          channel: 'stable'
          cache: true
      # 12
      - name: Get dependencies
        # run: flutter pub get
        run: flutter build apk --release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.HAJIRTOKEN}}

      # Runs a set of commands using the runners shell
      # - name: Start release build
      #   run: flutter build appbundle